<?php

namespace App\Traits;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Http\Exceptions\HttpResponseException;

trait APIValidationErrorsTrait
{
    protected function failedValidation(Validator $validator)
    {
        if ($this->wantsJson() || $this->is('api/*')){
            throw new HttpResponseException(response()->json([
                'success'   => false,
                'code'      => 422,
                'message'   => "Validation Error",
                'data'      => [],
                'errors'    => $validator->errors()->all()
            ],422));
        }else{
            parent::failedValidation($validator); // TODO: Change the autogenerated stub
        }
    }
}
